### ISSUE TITLE
Set Upper Limit for Transparency Slider

### ISSUE THREAD

**Issue by solvedbiscuit71** [kaushik54git/TransLuminate#1]
When the transparency slider is set to maximum, the entire screen becomes invisible, causing frustration among users who struggle to locate the slider. To prevent this issue, I suggest implementing an upper bound threshold on the slider's transparency setting.

**Comment by kaushik54git** [comment]
added an upper bound of 210, so that no one accidentally dim their screen too much

thanks for your suggestion
